# Header
nav:
  Home:
    href: /
    icon: home
  Archives:
    href: /archives
    icon: inbox
  About:
    href: /about
    icon: user
nav_style: icon # icon | text
nav_style_src: https://lf1-cdn-tos.bytegoofy.com/obj/iconpark/icons_23407_3.e1f4fb8d30cbe72d34c7e0443b651cfd.js

# Banner
banner:
avatar:

# Post
expert_len: 120

menu:
  Home: /
  Archives: /archives

# Read More text
excerpt_link: Read More

# Footer
footer:
  start_time: 2023

# I18n
i18n_dir: :lang

# Misc
google_analytics:
